services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 120s
      retries: 5
    networks:
        - goldlist
  web:
    build: .
    stdin_open: true 
    tty: true
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
        - goldlist

networks:
  goldlist:
    driver: bridge