# Generated by Django 5.0.1 on 2024-08-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goldlistmethod', '0001_initial'),
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebook_list', to='usermanager.studentuser'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goldlistmethod.pagesection'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagesection_list', to='goldlistmethod.notebook'),
        ),
        migrations.AddField(
            model_name='sentencelabel',
            name='pagesection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentencelabels', to='goldlistmethod.pagesection'),
        ),
        migrations.AddConstraint(
            model_name='sentencetranslation',
            constraint=models.UniqueConstraint(fields=('foreign_language_sentence', 'foreign_language_idiom', 'mother_language_idiom'), name='unique_sentence_translation'),
        ),
        migrations.AddField(
            model_name='sentencelabel',
            name='sentencetranslation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goldlistmethod.sentencetranslation'),
        ),
        migrations.AlterUniqueTogether(
            name='notebook',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='pagesection',
            unique_together={('group', 'created_at', 'distillation_at')},
        ),
    ]
