# Generated by Django 5.0.1 on 2024-08-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0004_notebook_created_by'),
        ('usermanager', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='goldlistmethod.institution'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='usermanager.professoruser'),
        ),
    ]
