# Generated by Django 5.0.1 on 2024-08-07 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0005_alter_classroom_institution_and_more'),
        ('usermanager', '0004_studentuser_student_classroom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Class Room', 'verbose_name_plural': 'Class Rooms'},
        ),
        migrations.AlterField(
            model_name='notebook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebook_list', to='usermanager.studentuser', verbose_name='Student'),
        ),
    ]
