# Generated by Django 5.0.1 on 2024-08-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0006_alter_classroom_options_alter_notebook_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='nome',
            new_name='name',
        ),
    ]
