# Generated by Django 5.0.1 on 2024-08-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0007_rename_nome_institution_name'),
        ('usermanager', '0010_alter_professoruser_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='usermanager.professoruser'),
        ),
    ]
