# Generated by Django 5.0.1 on 2024-08-08 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0010_alter_institution_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='max_qty_professor',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='max_qty_student',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
