# Generated by Django 5.0.1 on 2024-08-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0011_alter_institution_max_qty_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='equipment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
