# Generated by Django 5.0.1 on 2024-08-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0012_alter_classroom_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
