# Generated by Django 5.0.1 on 2024-08-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0013_alter_institution_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
    ]
