# Generated by Django 5.0.1 on 2024-08-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0014_alter_institution_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'institution')},
        ),
    ]
