# Generated by Django 5.0.1 on 2024-08-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0015_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'room_number', 'institution')},
        ),
    ]
