# Generated by Django 5.0.1 on 2024-08-09 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0016_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='abbr',
            field=models.CharField(default='Undefined', max_length=10, verbose_name='Abbreviation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
