# Generated by Django 5.0.1 on 2024-08-05 22:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('sentence_list_size', models.IntegerField(default=20)),
                ('days_period', models.IntegerField(default=15)),
                ('foreign_idiom', models.CharField(default='English', max_length=100)),
                ('mother_idiom', models.CharField(default='Portuguese Brazil', max_length=100)),
            ],
            options={
                'verbose_name': 'Notebook',
                'verbose_name_plural': 'Notebooks',
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('page_number', models.IntegerField()),
                ('group', models.CharField(choices=[('A', 'HEADLIST'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('NP', 'NP'), ('RM', 'RM')], default='A', max_length=2)),
                ('distillation_at', models.DateField(blank=True, null=True)),
                ('distillated', models.BooleanField(default=False)),
                ('distillation_actual', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
            },
        ),
        migrations.CreateModel(
            name='SentenceLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('translation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('memorized', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Sentence Label',
                'verbose_name_plural': 'Sentence Labels',
            },
        ),
        migrations.CreateModel(
            name='SentenceTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('foreign_language_sentence', models.CharField(max_length=200)),
                ('mother_language_sentence', models.CharField(max_length=200)),
                ('foreign_language_idiom', models.CharField(max_length=200)),
                ('mother_language_idiom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Sentence Translation',
                'verbose_name_plural': 'Sentence Translations',
            },
        ),
    ]
