# Generated by Django 5.0.1 on 2024-07-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencelabel',
            name='memorialized',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
