# Generated by Django 5.0.1 on 2024-02-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesectionsentenceassoc',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='_memorializeds',
            field=models.TextField(db_column='memorializeds', null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='_translated_sentences',
            field=models.TextField(db_column='translated_sentences', null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='distillated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
