# Generated by Django 5.0.1 on 2024-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0003_customuser_age'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sentencetranslation',
            constraint=models.UniqueConstraint(fields=('foreign_language_sentence', 'foreign_language_idiom', 'mother_language_idiom'), name='unique_sentence_translation'),
        ),
    ]
