# Generated by Django 5.0.1 on 2024-07-20 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0004_sentencetranslation_unique_sentence_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencelabel',
            name='sentencetranslation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goldlistmethod.sentencetranslation'),
        ),
    ]
