# Generated by Django 5.0.1 on 2024-07-22 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0005_alter_sentencelabel_sentencetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencelabel',
            name='pagesection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentencelabels', to='goldlistmethod.pagesection'),
        ),
    ]
