# Generated by Django 5.0.1 on 2024-07-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0006_alter_sentencelabel_pagesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='distillated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='distillation_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
