# Generated by Django 5.0.1 on 2024-07-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0007_alter_pagesection_distillated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='distillated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
