# Generated by Django 5.0.1 on 2024-07-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0008_alter_pagesection_distillated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='distillated',
            field=models.BooleanField(default=False),
        ),
    ]
