# Generated by Django 5.0.1 on 2024-07-28 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0009_alter_pagesection_distillated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
