# Generated by Django 5.0.1 on 2024-07-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0010_alter_pagesection_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagesection',
            unique_together={('group', 'created_at', 'distillation_at')},
        ),
    ]
