# Generated by Django 5.0.1 on 2024-07-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0011_alter_pagesection_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentencelabel',
            old_name='memorialized',
            new_name='memorized',
        ),
    ]
