# Generated by Django 5.0.1 on 2024-08-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0012_rename_memorialized_sentencelabel_memorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencelabel',
            name='memorized',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
