# Generated by Django 5.0.1 on 2024-08-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0013_alter_sentencelabel_memorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencelabel',
            name='translation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
