# Generated by Django 5.0.1 on 2024-08-05 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0003_institution_classroom'),
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='responsible_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_people', to='goldlistmethod.institution'),
        ),
        migrations.AddField(
            model_name='professoruser',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='goldlistmethod.institution'),
        ),
    ]
