# Generated by Django 5.0.1 on 2024-08-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_adminuser_responsible_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Admin', 'Admin'), ('Root', 'Root'), ('Undefined', 'Undefined')], default='Root', max_length=10),
        ),
    ]
