# Generated by Django 5.0.1 on 2024-08-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0005_alter_classroom_institution_and_more'),
        ('usermanager', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='student_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='goldlistmethod.classroom'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='responsible_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_people', to='goldlistmethod.institution'),
        ),
    ]
