# Generated by Django 5.0.1 on 2024-08-07 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0006_alter_classroom_options_alter_notebook_user'),
        ('usermanager', '0004_studentuser_student_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='responsible_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_people', to='goldlistmethod.institution', verbose_name='Responsible by'),
        ),
        migrations.AlterField(
            model_name='professoruser',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professors', to='goldlistmethod.institution'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='student_classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='goldlistmethod.classroom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
