# Generated by Django 5.0.1 on 2024-08-07 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0006_alter_classroom_options_alter_notebook_user'),
        ('usermanager', '0007_alter_adminuser_responsible_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='student_classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='goldlistmethod.classroom'),
        ),
    ]
