# Generated by Django 5.0.1 on 2024-08-07 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldlistmethod', '0006_alter_classroom_options_alter_notebook_user'),
        ('usermanager', '0008_alter_studentuser_student_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='responsible_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_people', to='goldlistmethod.institution', verbose_name='Responsible by'),
        ),
    ]
